-- Server-written, non-PII fare observations used to identify unusually good destination prices.
create table if not exists public.travel_price_observations (
  id bigint generated by default as identity primary key,
  provider text not null,
  origin_iata text not null,
  destination_key text not null,
  destination_name text not null,
  currency text not null,
  departure_month text,
  price numeric not null check (price >= 0),
  observed_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (provider, origin_iata, destination_key, currency, departure_month, observed_at)
);

create index if not exists travel_price_history_lookup
  on public.travel_price_observations(origin_iata, destination_key, currency, departure_month, observed_at desc);

alter table public.travel_price_observations enable row level security;

-- Clients receive only normalized deal responses from the authenticated Edge Function.
-- The service role owns observation inserts and baseline reads; no client policy is intentional.

insert into public.feature_flags(key, enabled, payload) values
  ('public_data_v1', true, '{}'),
  ('booking_stays_v1', true, '{}'),
  ('flight_deals_v1', true, '{}')
on conflict (key) do nothing;
